on:
  push:
    branches:
      - main
  pull_request:
name: django-tests6
jobs:
  system-tests:
    runs-on: ubuntu-latest

    services:
      emulator-0:
        image: gcr.io/cloud-spanner-emulator/emulator:latest
        ports:
          - 9010:9010

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Run Django tests
        run: sh django_test_suite.sh
        env:
          SPANNER_EMULATOR_HOST: localhost:9010
          GOOGLE_CLOUD_PROJECT: emulator-test-project
          GOOGLE_CLOUD_TESTS_CREATE_SPANNER_INSTANCE: true
          RUNNING_SPANNER_BACKEND_TESTS: 1
          SPANNER_TEST_INSTANCE: google-cloud-django-backend-tests
          DJANGO_TEST_APPS: model_fields queries.test_bulk_update queries.test_explain
