on:
  push:
    branches:
      - master
  pull_request:
name: django-tests9
jobs:
  system-tests:
    runs-on: ubuntu-latest

    services:
      emulator-0:
        image: gcr.io/cloud-spanner-emulator/emulator:latest
        ports:
          - 9010:9010

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run Django tests
        run: sh django_test_suite.sh
        env:
          SPANNER_EMULATOR_HOST: localhost:9010
          GOOGLE_CLOUD_PROJECT: emulator-test-project
          GOOGLE_CLOUD_TESTS_CREATE_SPANNER_INSTANCE: true
          RUNNING_SPANNER_BACKEND_TESTS: 1
          SPANNER_TEST_INSTANCE: google-cloud-django-backend-tests
          TEST_APPS: prefetch_related proxy_model_inheritance proxy_models queries queryset_pickle raw_query redirects_tests reserved_names reverse_lookup save_delete_hooks schema
