on:
  push:
    branches:
      - main
  pull_request:
name: django-tests0
jobs:
  system-tests:
    runs-on: ubuntu-latest

    services:
      emulator-0:
        image: gcr.io/cloud-spanner-emulator/emulator:latest
        ports:
          - 9010:9010

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Run Django tests
        run: sh django_test_suite.sh
        env:
          SPANNER_EMULATOR_HOST: localhost:9010
          GOOGLE_CLOUD_PROJECT: emulator-test-project
          GOOGLE_CLOUD_TESTS_CREATE_SPANNER_INSTANCE: true
          RUNNING_SPANNER_BACKEND_TESTS: 1
          SPANNER_TEST_INSTANCE: google-cloud-django-backend-tests
          DJANGO_TEST_APPS: admin_changelist admin_ordering aggregation choices distinct_on_fields expressions_window fixtures_model_package datetimes custom_methods generic_inline_admin field_defaults datatypes empty m2o_recursive many_to_one_null migration_test_data_persistence admin_docs invalid_models_tests migrate_signals model_forms.test_uuid model_forms.test_modelchoicefield syndication_tests view_tests update test_utils select_related_onetoone sessions_tests
