on:
  push:
    branches:
      - master
  pull_request:
name: django-tests
jobs:
  system-tests:
    runs-on: ubuntu-latest

    services:
      emulator-0:
        image: gcr.io/cloud-spanner-emulator/emulator:latest
        ports:
          - 9010:9010
      emulator-1:
        image: gcr.io/cloud-spanner-emulator/emulator:latest
        ports:
          - 9011:9010
      emulator-2:
        image: gcr.io/cloud-spanner-emulator/emulator:latest
        ports:
          - 9012:9010
      emulator-3:
        image: gcr.io/cloud-spanner-emulator/emulator:latest
        ports:
          - 9013:9010
      emulator-4:
        image: gcr.io/cloud-spanner-emulator/emulator:latest
        ports:
          - 9014:9010
      emulator-5:
        image: gcr.io/cloud-spanner-emulator/emulator:latest
        ports:
          - 9015:9010
      emulator-6:
        image: gcr.io/cloud-spanner-emulator/emulator:latest
        ports:
          - 9016:9010
      emulator-7:
        image: gcr.io/cloud-spanner-emulator/emulator:latest
        ports:
          - 9017:9010

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run Django tests
        run: sh django_test_suite.sh
        env:
          SPANNER_EMULATOR_HOST: localhost:9010
          GOOGLE_CLOUD_PROJECT: emulator-test-project
          GOOGLE_CLOUD_TESTS_CREATE_SPANNER_INSTANCE: true
          RUNNING_SPANNER_BACKEND_TESTS: 1
          DJANGO_WORKER_INDEX: 0
          DJANGO_WORKER_COUNT: 1
          SPANNER_TEST_INSTANCE: google-cloud-django-backend-tests
